[build]
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

# Form submission redirect
[[redirects]]
  from = "/contact"
  to = "/contact?success=true"
  status = 303
  force = false
  conditions = {Role = ["form-submission"]}